version: '3'

services:

    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: <пароль>
      volumes:
        - bornes:/var/lib/postgresql/data
      ports:
        - '5432:5432'

    bot:
      build: .
      command:
#           bash -c "alembic revision --autogenerate -m "Innit" && alembic upgrade head && cd bot && python server.py"
           bash -c "cd bot && python server.py"

      depends_on:
        - db


volumes:
  bornes:



