version: '3'

services:

    db:
      image: crazycapivara/postgres-postgis:10-pgh3
      restart: always
      environment:
        POSTGRES_PASSWORD: vlad
      volumes:
        - bornes:/var/lib/postgresql/data
      ports:
        - '5432:5432'

    bot:
      build: ..
      command: bash -c "alembic revision --autogenerate -m "Innit" && alembic upgrade head && cd bot && ls && python server.py"
      depends_on:
        - db


volumes:
  bornes:






#  bot_db:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_PASSWORD=vlad
#      - POSTGRES_USER=vlad
#      - POSTGRES_DB=db_bot
#    volumes:
#      - pg_project:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#
#volumes:
#  pg_project:


